server:
  port: 8989
  servlet:
    context-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.86.151:3306/vueblog?characterEncoding=utf-8
    username: root
    password: root
  resources:
    static-locations: classpath:/static



mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: world.lixiang.entity
logging:
  level:
    world:
      lixiang:
        dao: debug
